package Parallell_programming;

import java.util.Random;
import java.util.concurrent.Semaphore;
import java.io.IOException;

public class Criador extends Thread {

    private String texto;
    private final Semaphore a;
    private final Semaphore b;

    public Criador(Semaphore a, Semaphore b) {
        this.a = a;
        this.b = b;
    }
    // method to get the text generated by the thread.
    public String pegar_texto() {
        return texto;
    }

    // method to randomly generate the sequence.
    public void gerar_texto() throws IOException {
        this.texto = "";
        int cont = 0;
        Random random = new Random();
        while (cont < 12) {
            char caracter = ' ';
            caracter = (char) (97 + random.nextInt(2));
            this.texto += caracter;
            cont++;
        }
        System.out.println("Sequência: " + texto);
    }

    // default method used to perform the signaling action between semaphores
    // and also to execute the necessary methods of the thread.
    public void run() {
        try {
            while (true) {
                a.acquire();
                gerar_texto();
                b.release();
            }
        } catch (InterruptedException | IOException e) {
            e.printStackTrace();
        }

    }

}